spring:
  application:
    name: music
  datasource:
    url: jdbc:mysql://localhost:3306/music_player?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  storage:
    root-path: ${user.dir}/../music-player-files
